# Generated by Django 4.2.25 on 2025-11-03 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='打印机名称')),
                ('ip_address', models.CharField(max_length=15, verbose_name='IP地址')),
                ('port', models.IntegerField(default=7125, verbose_name='端口')),
                ('model', models.CharField(blank=True, max_length=100, verbose_name='型号')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '打印机',
                'verbose_name_plural': '打印机',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrintJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, verbose_name='文件名')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('printing', '打印中'), ('completed', '已完成'), ('failed', '失败'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('progress', models.FloatField(default=0.0, verbose_name='进度')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('printer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moondev.printer', verbose_name='打印机')),
            ],
            options={
                'verbose_name': '打印任务',
                'verbose_name_plural': '打印任务',
                'ordering': ['-created_at'],
            },
        ),
    ]
